site_name: Test Notebook 

nav:
  - Home: index.md
  - About: about.md
  - Chapter 1:
    - Introduction: chapter1/introduction.md

theme:
  name: material 

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
