= Links Index
:revealjsdir: https://cdn.jsdelivr.net/npm/reveal.js@4.3.1
:revealjs_theme: none
:revealjs_customtheme: styles/custom-theme.css
:customcss: styles/custom-theme-custom.css
ifndef::imagesdir[:imagesdir: images]
:revealjs_transition: slide
:revealjs_width: 1600
:revealjs_height: 1200
:revealjs_margin: 0
:revealjs_history: true
:revealjs_hash: true

[%notitle]
== Table of Contents

toc::[]

== First Diagram

[ditaa,asciidoctor-diagram-process,width=1000px]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        |---+ Asciidoctor +--->|               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....

== Second Diagram

Here's a PlantUML diagram:

[plantuml, this-test-diagram, width=1000px, svg]
....
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
@enduml
....

== Third Diagram

[plantuml, this-sequence-diagram, width=1200px, svg]
....
@startuml
participant User
User -> A: DoWork
activate A
A -> B: << createRequest >>
activate B
B -> C: DoWork
activate C
C --> B: WorkDone
destroy C
B --> A: RequestCreated
deactivate B
A -> User: Done
deactivate A
@enduml
....

[plantuml, this-sequence-diagram, svg]
----
@startuml
participant User
User -> A: DoWork
activate A
A -> B: << createRequest >>
activate B
B -> C: DoWork
activate C
C --> B: WorkDone
destroy C
B --> A: RequestCreated
deactivate B
A -> User: Done
deactivate A
@enduml
----

== Diagram Example

[blockdiag]
....
blockdiag {
  Kroki -> generates -> "Block diagrams";

  Kroki [color = "greenyellow"];
  "Block diagrams" [color = "pink"];
}
....


== Diagram

[mermaid,abcd-flowchart,svg]
....
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
....


== Diagram

[graphviz]
....
digraph foo {
  node [style=rounded]
  node1 [shape=box]
  node2 [fillcolor=yellow, style="rounded,filled", shape=diamond]
  node3 [shape=record, label="{ a | b | c }"]

  node1 -> node2 -> node3
}
....

== Diagram

[plantuml, this-test-diagram, svg]
....
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
@enduml
....

== diagram

[plantuml, this-sequence-diagram, svg]
....
@startuml
participant User
User -> A: DoWork
activate A
A -> B: << createRequest >>
activate B
B -> C: DoWork
activate C
C --> B: WorkDone
destroy C
B --> A: RequestCreated
deactivate B
A -> User: Done
deactivate A
@enduml
....

== Diagram

[plantuml, this-sequence-diagram, svg]
----
@startuml
participant User
User -> A: DoWork
activate A
A -> B: << createRequest >>
activate B
B -> C: DoWork
activate C
C --> B: WorkDone
destroy C
B --> A: RequestCreated
deactivate B
A -> User: Done
deactivate A
@enduml
----

== Diagram

[ditaa,asciidoctor-diagram-process]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        |---+ Asciidoctor +--->|               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....

== Diagram-as-code

All these architecture diagrams use PlantUML, with a custom skin to fit the theme.

[.maxed-image]
=== Sequence diagram

[plantuml, rma-sequence-diagram]
....
participant User
User -> A: DoWork
activate A
A -> B: << createRequest >>
activate B
B -> C: DoWork
activate C
C --> B: WorkDone
destroy C
B --> A: RequestCreated
deactivate B
A -> User: Done
deactivate A
....

=== Source

[source,asciidoc]
----
[plantuml, rma-sequence-diagram, png]
....
participant User
User -> A: DoWork
activate A
A -> B: << createRequest >>
activate B
B -> C: DoWork
activate C
C --> B: WorkDone
destroy C
B --> A: RequestCreated
deactivate B
A -> User: Done
deactivate A
....
----

[.maxed-image]
=== Use case diagram

[plantuml, rma-use-case-diagram, png]
....
left to right direction

actor developer
database repo as "central\nrepo"
agent jenkins as "Jenkins"

rectangle admin as "Gerrit / GitLab" {
    agent ui as "front"
    database repo_local as "local\nrepo"
}

developer --> ui : push
ui --> repo_local : push
ui -left-> jenkins: "\npush "
ui ..> repo : replication
....

=== Source

[source,asciidoc]
----
[plantuml, rma-use-case-diagram, png]
....
left to right direction

actor developer
database repo as "central\nrepo"
agent jenkins as "Jenkins"

rectangle admin as "Gerrit / GitLab" {
    agent ui as "front"
    database repo_local as "local\nrepo"
}

developer --> ui : push
ui --> repo_local : push
ui -left-> jenkins: "\npush "
ui ..> repo : replication
....
----

[.maxed-image]
=== Class diagram

[plantuml, rma-class-diagram, png]     
....
abstract class ArrayList {
  Object[] elementData
  size()
}
enum TimeUnit {
  DAYS
  HOURS
  MINUTES
}
Interface BaseClass

namespace net.dummy {
    .BaseClass <|-- Person
    Meeting o-- Person

    .BaseClass <|- Meeting
}
namespace net.foo {
  net.dummy.Person  <|- Person
  .BaseClass <|-- Person

  net.dummy.Meeting o-- Person
}
BaseClass <|-- net.unused.Person
....

=== Source

[source,asciidoc]
----
[plantuml, rma-class-diagram, png]     
....
abstract class ArrayList {
  Object[] elementData
  size()
}
enum TimeUnit {
  DAYS
  HOURS
  MINUTES
}
Interface BaseClass

namespace net.dummy {
    .BaseClass <|-- Person
    Meeting o-- Person

    .BaseClass <|- Meeting
}
namespace net.foo {
  net.dummy.Person  <|- Person
  .BaseClass <|-- Person

  net.dummy.Meeting o-- Person
}
BaseClass <|-- net.unused.Person
....
----

[.maxed-image]
=== Activity diagram

[plantuml, activity-diagram, png]
....
(*) --> "Initialization"

if "Some Test" then
  -->[true] "Some Activity"
  --> "Another activity"
  -right-> (*)
else
  ->[false] "Something else"
  -->[Ending process] (*)
endif
....

=== Source

[source,asciidoc]
----
[plantuml, activity-diagram, png]
....
(*) --> "Initialization"

if "Some Test" then
  -->[true] "Some Activity"
  --> "Another activity"
  -right-> (*)
else
  ->[false] "Something else"
  -->[Ending process] (*)
endif
....
----

[.maxed-image]
=== Component diagram

[plantuml, rma-component-diagram, png]     
....
package "Some Group" {
  HTTP - [First Component]
  [Another Component]
}
rectangle "Other Groups" {
  FTP - [Second Component]
  [First Component] --> FTP
} 
cloud {
  [Example 1]
}
database "MySql" {
  folder "This is my folder" {
    [Folder 3]
  }
  frame "Foo" {
    [Frame 4]
  }
}
[Another Component] --> [Example 1]
[Example 1] -right-> [Folder 3]
[Folder 3] --> [Frame 4]
....

=== Source

[source,asciidoc]
----
[plantuml, rma-component-diagram, png]     
....
package "Some Group" {
  HTTP - [First Component]
  [Another Component]
}
rectangle "Other Groups" {
  FTP - [Second Component]
  [First Component] --> FTP
} 
cloud {
  [Example 1]
}
database "MySql" {
  folder "This is my folder" {
    [Folder 3]
  }
  frame "Foo" {
    [Frame 4]
  }
}
[Another Component] --> [Example 1]
[Example 1] -right-> [Folder 3]
[Folder 3] --> [Frame 4]
....
----

[.maxed-image]
=== State diagram

[plantuml, rma-state-diagram]     
....
[*] -left-> State1
State1 -left-> State2 : Succeeded
State1 --> [*] : Aborted
State2 --> State3 : Succeeded
State2 --> [*] : Aborted
state State3 {
  state "Accumulate Enough Data\nLong State Name" as long1
  long1 : Just a test
  [*] --> long1
  long1 --> long1 : New Data
  long1 --> ProcessData : Enough Data
}
State3 --> State3 : Failed
State3 --> [*] : Succeeded
State3 --> [*] : Aborted
....

=== Source

[source,asciidoc]
----
[plantuml, rma-state-diagram]     
....
[*] -left-> State1
State1 -left-> State2 : Succeeded
State1 --> [*] : Aborted
State2 --> State3 : Succeeded
State2 --> [*] : Aborted
state State3 {
  state "Accumulate Enough Data\nLong State Name" as long1
  long1 : Just a test
  [*] --> long1
  long1 --> long1 : New Data
  long1 --> ProcessData : Enough Data
}
State3 --> State3 : Failed
State3 --> [*] : Succeeded
State3 --> [*] : Aborted
....
----

[.maxed-image]
=== Work Breakdown Structure

[plantuml, wbs]     
....
@startwbs
* Business Process Modelling WBS
** Launch the project
*** Stakeholder Research
*** Implementation Plan
** Design phase
*** AsIs Processes Completed
****< AsIs Processes Completed1
****> AsIs Processes Completed2
***< AsIs performance metrics
***< Identify Quick Wins
@endwbs
....

=== Source

[source,asciidoc]
----
[plantuml, wbs]     
....
@startwbs
* Business Process Modelling WBS
** Launch the project
*** Stakeholder Research
*** Implementation Plan
** Design phase
*** AsIs Processes Completed
****< AsIs Processes Completed1
****> AsIs Processes Completed2
***< AsIs performance metrics
***< Identify Quick Wins
@endwbs
....
----

[.maxed-image]
=== Timing diagram

[plantuml, timing, png]     
....
'skinparam backgroundColor white # does not work
robust "Web Browser" as WB
concise "Web User" as WU
WB is Initializing
WU is Absent
@WB
0 is idle
+200 is Processing
+100 is Waiting
WB@0 <-> @50 : {50 ms lag}
@WU
WU -> WB : URL
0 is Waiting #white
+500 is ok #white
@200 <-> @+150 : {150 ms}
....

=== Source

[source,asciidoc]
----
[plantuml, timing, png]     
....
'skinparam backgroundColor white # does not work
robust "Web Browser" as WB
concise "Web User" as WU
WB is Initializing
WU is Absent
@WB
0 is idle
+200 is Processing
+100 is Waiting
WB@0 <-> @50 : {50 ms lag}
@WU
WU -> WB : URL
0 is Waiting #white
+500 is ok #white
@200 <-> @+150 : {150 ms}
....
----

[.maxed-image]
=== Mind Map

[plantuml, mindmap, png]     
....
@startmindmap
* Debian
** Ubuntu
*** Linux Mint
*** Kubuntu
*** Lubuntu
*** KDE Neon
** LMDE
** SolydXK
** SteamOS
** Raspbian with a very long name
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio
@endmindmap
....

=== Source

[source,asciidoc]
----
[plantuml, mindmap, png]     
....
@startmindmap
* Debian
** Ubuntu
*** Linux Mint
*** Kubuntu
*** Lubuntu
*** KDE Neon
** LMDE
** SolydXK
** SteamOS
** Raspbian with a very long name
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio
@endmindmap
....
----


=== asciitosvg

[a2s, format="svg"]
....
.-------------------------.
|                         |
| .---.-. .-----. .-----. |
| | .-. | +-->  | |  <--| |
| | '-' | |  <--| +-->  | |
| '---'-' '-----' '-----' |
|  ascii     2      svg   |
|                         |
'-------------------------'
....

== PlantUML Sequence Diagrams

[.maxed-image]
=== Sequence with participants

[plantuml, sequence-with-participants, png]     
....
@startuml
participant Participant as Foo
actor       Actor       as Foo1
boundary    Boundary    as Foo2
control     Control     as Foo3
entity      Entity      as Foo4
database    Database    as Foo5
collections Collections as Foo6
queue       Queue       as Foo7
Foo -> Foo1 : To actor 
Foo -> Foo2 : To boundary
Foo -> Foo3 : To control
Foo -> Foo4 : To entity
Foo -> Foo5 : To database
Foo -> Foo6 : To collections
Foo -> Foo7: To queue
@enduml
....

[.maxed-image]
=== Basic messaging

[plantuml, basic-messaging, png]
....
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
@enduml
....

[.maxed-image]
=== Lifeline activation

[plantuml, lifeline-activation, png]
....
@startuml
participant User

User -> A: DoWork
activate A
A -> B: << createRequest >>
activate B
B -> C: DoWork
activate C
C --> B: WorkDone
destroy C
B --> A: RequestCreated
deactivate B
A -> User: Done
deactivate A
@enduml
....

[.maxed-image]
=== Grouping messages

[plantuml, grouping-messages, png]
....
@startuml
Alice -> Bob: Authentication Request

alt successful case
    Bob -> Alice: Authentication Accepted
else some kind of failure
    Bob -> Alice: Authentication Failure
    group My own label
        Alice -> Log : Log attack start
        loop 1000 times
            Alice -> Bob: DNS Attack
        end
        Alice -> Log : Log attack end
    end
else Another type of failure
    Bob -> Alice: Please repeat
end
@enduml
....

[.maxed-image]
=== Participant with colors and long names

[plantuml, participant-colors, png]
....
 	

@startuml
actor Bob #red
' The only difference between actor
'and participant is the drawing
participant Alice
participant "I have a really\nlong name" as L #99FF99
/' You can also declare:
   participant L as "I have a really\nlong name"  #99FF99
  '/

Alice->Bob: Authentication Request
Bob->Alice: Authentication Response
Bob->L: Log transaction
@enduml
....

[.maxed-image]
=== Message to self

[plantuml, message-to-self, png]
....
@startuml
Alice -> Alice: This is a signal to self.\nIt also demonstrates\nmultiline \ntext
@enduml
....

[.maxed-image]
=== Arrow styles

[plantuml, arrow-styles, png]
....
@startuml
Bob ->x Alice
Bob -> Alice
Bob ->> Alice
Bob -\ Alice
Bob \\- Alice
Bob //-- Alice
Bob ->o Alice
Bob o\\-- Alice
Bob <-> Alice
Bob <->o Alice
@enduml
....

[.maxed-image]
=== Colored arrows

[plantuml, colored-arrows, png]
....
@startuml
Bob -[#red]> Alice : hello
Alice -[#0000FF]-> Bob : ok
@enduml
....

[.maxed-image]
=== Message numbering

[plantuml, message-numbering, png]
....
@startuml
autonumber
Bob -> Alice : Authentication Request
Bob <- Alice : Authentication Response

autonumber 15
Bob -> Alice : Another authentication Request
Bob <- Alice : Another authentication Response

autonumber 40 10
Bob -> Alice : Yet another authentication Request
Bob <- Alice : Yet another authentication Response
@enduml
....

[.maxed-image]
=== Page title

[plantuml, page-title, png]
....
@startuml
title __Simple__ communication example

Alice -> Bob: Authentication Request
Bob -> Alice: Authentication Response
@enduml
....

[.maxed-image]
=== Complex grouping with multiple conditions

[plantuml, complex-grouping, png]
....
@startuml
Alice -> Bob: Authentication Request
alt successful case
    Bob -> Alice: Authentication Accepted
else some kind of failure
    Bob -> Alice: Authentication Failure
    group My own label
        Alice -> Log: Log attack start
        loop 1000 times
            Alice -> Bob: DNS Attack
        end
        Alice -> Log: Log attack end
    end
else Another type of failure
    Bob -> Alice: Please repeat
end
@enduml
....

[.maxed-image]
=== Nested grouping with parallel processes

[plantuml, nested-grouping, png]
....
@startuml
participant User
participant A
participant B
participant C

User -> A: Start Process
activate A
    par Processing Track 1
        A -> B: Request Data
        activate B
            B -> C: Fetch Details
            activate C
            C --> B: Return Information
            deactivate C
        B --> A: Data Response
        deactivate B
    else Processing Track 2
        A -> A: Internal Computation
    end
A --> User: Process Complete
deactivate A
@enduml
....

[.maxed-image]
=== Optional and break scenarios

[plantuml, optional-break, png]
....
@startuml
Alice -> Bob: Request
opt Valid Request
    Bob -> Alice: Process Request
    alt Successful
        Bob -> Alice: Confirmation
    else Failure
        Bob -> Alice: Error Message
        break Processing Error
            Bob -> Log: Log Error
        end
    end
else Invalid Request
    Bob -> Alice: Reject Request
end
@enduml
....

[.maxed-image]
=== Advanced lifeline activation

[plantuml, advanced-lifeline, png]
....
@startuml
autoactivate on
actor User
participant AuthService
database UserDB

User -> AuthService: Login Request
AuthService -> UserDB: Validate Credentials
UserDB --> AuthService: Credential Status
alt Authentication Successful
    AuthService -> AuthService: Generate Token
    AuthService --> User: Login Token
else Authentication Failed
    AuthService --> User: Access Denied
    destroy AuthService
end
@enduml
....

== PlantUML MindMap Diagrams

[.maxed-image]
=== OrgMode syntax

[plantuml, mindmap-orgmode, png]
....
@startmindmap
* Debian
** Ubuntu
*** Linux Mint
*** Kubuntu
*** Lubuntu
*** KDE Neon
** LMDE
** SolydXK
** SteamOS
** Raspbian with a very long name
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio
@endmindmap
....

[.maxed-image]
=== Markdown syntax

[plantuml, mindmap-markdown, png]
....
@startmindmap
* root node
	* some first level node
		* second level node
		* another second level node
	* another first level node
@endmindmap
....

[.maxed-image]
=== Arithmetic notation

[plantuml, mindmap-arithmetic, png]
....
@startmindmap
+ OS
++ Ubuntu
+++ Linux Mint
+++ Kubuntu
+++ Lubuntu
+++ KDE Neon
++ LMDE
++ SolydXK
++ SteamOS
++ Raspbian
-- Windows 95
-- Windows 98
-- Windows NT
--- Windows 8
--- Windows 10
@endmindmap
....

[.maxed-image]
=== Multilines example

[plantuml, mindmap-multilines, png]
....
@startmindmap
* Class Templates
**:Example 1
<code>
template <typename T>
class cname{
void f1()<U+003B>
...
}
</code>
;
**:Example 2
<code>
other template <typename T>
class cname{
...
</code>
;
@endmindmap
....

[.maxed-image]
=== Color inline example

[plantuml, mindmap-colors, png]
....
@startmindmap
*[#Orange] Colors
**[#lightgreen] Green
**[#FFBBCC] Rose
**[#lightblue] Blue
@endmindmap
....

[.maxed-image]
=== Removing boxes with underscore

[plantuml, mindmap-no-boxes, png]
....
@startmindmap
* root node
** some first level node
***_ second level node
***_ another second level node
***_ foo
***_ bar
***_ foobar
** another first level node
@endmindmap
....

[.maxed-image]
=== Word wrap example

[plantuml, mindmap-wordwrap, png]
....
@startmindmap
<style>
node {
    MaximumWidth 100
    Padding 12
    BackgroundColor gold
}
</style>
* Long Text Demonstration
** This is an example of how PlantUML can automatically wrap long text within mindmap nodes
*** Breaking text into manageable segments
*** Improving readability of complex mind maps
@endmindmap
....

[.maxed-image]
=== Creole formatting in mindmap

[plantuml, mindmap-creole, png]
....
@startmindmap
* Formatting Examples
**:==Creole Styles
   This is **bold**
   This is //italics//
   This is __underlined__ ;
** HTML-like Formatting
**:This is <b>bold</b>
   This is <color:blue>Blue text</color> ;
@endmindmap
....


== PlantUML Entity Relation Diagrams

[.maxed-image]
=== Minimal vertical example

[plantuml, er-vertical, png]
....
@startchen

entity Person {
}
entity Location {
}
relationship Birthplace {
}

Person -N- Birthplace
Birthplace -1- Location

@endchen
....

[.maxed-image]
=== Minimal horizontal example

[plantuml, er-horizontal, png]
....
@startchen
left to right direction

entity Person { 
}
entity Location { 
}
relationship Birthplace { 
}

Person -N- Birthplace
Birthplace -1- Location
@endchen
....

[.maxed-image]
=== Entities with attributes

[plantuml, er-attributes, png]
....
@startchen
entity DIRECTOR {
  Name {
    Fname
    Lname
  }
  Born
  Died
  Age
}
entity MOVIE {
  Title
  Released
  Code
}
@endchen
....

[.maxed-image]
=== Key and multi-valued attributes

[plantuml, er-key-attributes, png]
....
@startchen
entity DIRECTOR {
  Number : INTEGER <<key>>
  Name {
    Fname : STRING
    Lname : STRING
  }
  Born : DATE
  Died : DATE
  Age : INTEGER
}
entity CUSTOMER {
  Number : INTEGER <<key>>
  Bonus : REAL <<derived>>
  Name : STRING <<multi>>
}
@endchen
....

[.maxed-image]
=== Relationships with cardinality

[plantuml, er-cardinality, png]
....
@startchen
entity CUSTOMER {
  Number <<key>>
  Name
}
entity MOVIE {
  Code <<key>>
}
relationship RENTED_TO {
  Date
}
RENTED_TO -(1,N)- CUSTOMER
RENTED_TO -(0,1)- MOVIE
@endchen
....

[.maxed-image]
=== Weak entity example

[plantuml, er-weak-entity, png]
....
@startchen

entity PARENT {
  Number <<key>>
  Name
}

entity CHILD <<weak>> {
  Name <<key>>
  Age
}

relationship PARENT_OF <<identifying>> {
}

PARENT_OF -1- PARENT
PARENT_OF =N= CHILD

@endchen
....

[.maxed-image]
=== Subclasses and categories

[plantuml, er-subclasses, png]
....
@startchen

entity CUSTOMER {
}

entity PARENT {
}

entity MEMBER {
}

CUSTOMER ->- PARENT
MEMBER -<- CUSTOMER

@endchen
....

== PlantUML DITAA Diagrams

[.maxed-image]
=== Basic DITAA diagram

[ditaa, ditaa-basic, png]
....
+--------+   +-------+    +-------+
|        +---+ ditaa +--> |       |
|  Text  |   +-------+    |diagram|
|Document|   |!magic!|    |       |
|     {d}|   |       |    |       |
+---+----+   +-------+    +-------+
     :                         ^
     |       Lots of work      |
     +-------------------------+
....

[.maxed-image]
=== DITAA with colors and symbols

[ditaa, ditaa-colors, png]
....
+---------+  /--------\   +-------+
| cBLU    +--+cAAA    +---+Version|
|         |  |  Data  |   |   V3  |
|    +----+  |  Base  |   |cRED{d}|
|    |cPNK|  |     {s}|   +-------+
|    |    |  \---+----+    +-------+
+----+----+               |       |
                          +-------+
....

[.maxed-image]
=== DITAA remove separator

[ditaa, ditaa-no-separator, png]
....
+---------+  /--------\   +-------+
| cBLU    +--+cAAA    +---+Version|
|         |  |  Data  |   |   V3  |
|    +----+  |  Base  |   |cRED{d}|
|    |cPNK|  |     {s}|   +-------+
|    |    |  \---+----+    +-------+
+----+----+               |       |
                          +-------+
....

[.maxed-image]
=== DITAA no shadows and scaled

[ditaa, ditaa-no-shadows-scaled, png]
....
+---------+  /--------\   +-------+
| cBLU    +--+cAAA    +---+Version|
|         |  |  Data  |   |   V3  |
|    +----+  |  Base  |   |cRED{d}|
|    |cPNK|  |     {s}|   +-------+
|    |    |  \---+----+    +-------+
+----+----+               |       |
                          +-------+
....


== PlantUML Gantt Diagrams

[.maxed-image]
=== Basic task duration

[plantuml, gantt-basic, png]
....
@startgantt
[Prototype design] requires 15 days
[Test prototype] requires 10 days
@endgantt
....

[.maxed-image]
=== Project start date

[plantuml, gantt-start-date, png]
....
@startgantt
Project starts 2020-07-01
[Prototype design] starts 2020-07-01
[Test prototype] starts 2020-07-16
@endgantt
....

[.maxed-image]
=== Task dependencies

[plantuml, gantt-dependencies, png]
....
@startgantt
[Prototype design] requires 15 days
[Test prototype] requires 10 days
[Test prototype] starts at [Prototype design]'s end
@endgantt
....

[.maxed-image]
=== Task aliases

[plantuml, gantt-aliases, png]
....
@startgantt
[Prototype design] as [D] requires 15 days
[Test prototype] as [T] requires 10 days
[T] starts at [D]'s end
@endgantt
....

[.maxed-image]
=== Color customization

[plantuml, gantt-colors, png]
....
@startgantt
[Prototype design] requires 13 days
[Test prototype] requires 4 days
[Test prototype] starts at [Prototype design]'s end
[Prototype design] is colored in Fuchsia/FireBrick
[Test prototype] is colored in GreenYellow/Green
@endgantt
....

[.maxed-image]
=== Task completion percentage

[plantuml, gantt-completion, png]
....
@startgantt
[foo] requires 21 days
[foo] is 40% completed
[bar] requires 30 days and is 10% complete
@endgantt
....

[.maxed-image]
=== Milestones

[plantuml, gantt-milestones, png]
....
@startgantt
[Test prototype] requires 10 days
[Prototype completed] happens at [Test prototype]'s end
[Setup assembly line] requires 12 days
[Setup assembly line] starts at [Test prototype]'s end
@endgantt
....

[.maxed-image]
=== Working days and weekends

[plantuml, gantt-working-days, png]
....
@startgantt
saturday are closed 
sunday are closed 
2022-07-04 to 2022-07-15 is closed  
Project starts 2022-06-27 
[task1] starts at 2022-06-27 and requires 1 week 
[task2] starts 2 working days after [task1]'s end and requires 3 days  
@endgantt
....

[.maxed-image]
=== Task grouping with resources

[plantuml, gantt-resources, png]
....
@startgantt
[Task1] on {Alice} requires 10 days
[Task2] on {Bob:50%} requires 2 days
then [Task3] on {Alice:25%} requires 1 days
then [Task4] on {Alice:25%} {Bob} requires 1 days
@endgantt
....

[.maxed-image]
=== Complex project example

[plantuml, gantt-complex, png]
....
@startgantt
[Prototype design] requires 13 days and is colored in Lavender/LightBlue 
[Test prototype] requires 9 days and is colored in Coral/Green and starts 3 days after [Prototype design]'s end 
[Write tests] requires 5 days and ends at [Prototype design]'s end 
[Hire tests writers] requires 6 days and ends at [Write tests]'s start 
[Init and write tests report] is colored in Coral/Green 
[Init and write tests report] starts 1 day before [Test prototype]'s start and ends at [Test prototype]'s end 
@endgantt
....

== PlantUML JSON Diagrams

[.maxed-image]
=== Basic JSON object

[plantuml, json-basic, png]
....
@startjson
{
    "fruit":"Apple",
    "size":"Large",
    "color": ["Red", "Green"]
}
@endjson
....

[.maxed-image]
=== Complex JSON structure

[plantuml, json-complex, png]
....
@startjson
{
   "firstName": "John",
   "lastName": "Smith",
   "isAlive": true,
   "age": 27,
   "address": {
     "streetAddress": "21 2nd Street",
     "city": "New York",
     "state": "NY",
     "postalCode": "10021-3100"
   },
   "phoneNumbers": [
     {
       "type": "home",
       "number": "212 555-1234"
     },
     {
       "type": "office",
       "number": "646 555-4567"
     }
   ],
   "children": [],
   "spouse": null
}
@endjson
....

[.maxed-image]
=== JSON with highlighted elements

[plantuml, json-highlighted, png]
....
@startjson
#highlight "lastName"
#highlight "address" / "city"
#highlight "phoneNumbers" / "0" / "number"
{
   "firstName": "John",
   "lastName": "Smith",
   "isAlive": true,
   "age": 28,
   "address": {
     "streetAddress": "21 2nd Street",
     "city": "New York",
     "state": "NY",
     "postalCode": "10021-3100"
   },
   "phoneNumbers": [
     {
       "type": "home",
       "number": "212 555-1234"
     },
     {
       "type": "office",
       "number": "646 555-4567"
     }
   ],
   "children": [],
   "spouse": null
}
@endjson
....

[.maxed-image]
=== JSON with custom styles

[plantuml, json-styled, png]
....
@startjson
<style>
   .h1 {
     BackGroundColor green
     FontColor white
     FontStyle italic
   }
   .h2 {
     BackGroundColor red
     FontColor white
     FontStyle bold
   }
</style>
#highlight "lastName"
#highlight "address" / "city" <<h1>>
#highlight "phoneNumbers" / "0" / "number" <<h2>>
{
   "firstName": "John",
   "lastName": "Smith",
   "isAlive": true,
   "age": 28,
   "address": {
     "streetAddress": "21 2nd Street",
     "city": "New York",
     "state": "NY",
     "postalCode": "10021-3100"
   },
   "phoneNumbers": [
     {
       "type": "home",
       "number": "212 555-1234"
     },
     {
       "type": "office",
       "number": "646 555-4567"
     }
   ],
   "children": [],
   "spouse": null
}
@endjson
....

== PlantUML YAML Diagrams

[.maxed-image]
=== Basic YAML diagram

[plantuml, yaml-basic, png]
....
@startyaml
fruit: Apple
size: Large
color:
    - Red
    - Green
@endyaml
....

[.maxed-image]
=== Complex YAML example

[plantuml, yaml-complex, png]
....
@startyaml
doe: "a deer, a female deer"
ray: "a drop of golden sun"
pi: 3.14159
xmas: true
french-hens: 3
calling-birds:
    - huey
    - dewey
    - louie
    - fred
xmas-fifth-day:
    calling-birds: four
    french-hens: 3
    golden-rings: 5
    partridges:
        count: 1
        location: "a pear tree"
    turtle-doves: two
@endyaml
....

[.maxed-image]
=== YAML with special characters

[plantuml, yaml-special-keys, png]
....
@startyaml
@fruit: Apple
$size: Large
&color: Red
❤: Heart
‰: Per mille
@endyaml
....

[.maxed-image]
=== YAML with highlighted elements

[plantuml, yaml-highlighted, png]
....
@startyaml
#highlight "french-hens"
#highlight "xmas-fifth-day" / "partridges"
doe: "a deer, a female deer"
ray: "a drop of golden sun"
pi: 3.14159
xmas: true
french-hens: 3
calling-birds:
    - huey
    - dewey
    - louie
    - fred
xmas-fifth-day:
    calling-birds: four
    french-hens: 3
    golden-rings: 5
    partridges:
        count: 1
        location: "a pear tree"
    turtle-doves: two
@endyaml
....

[.maxed-image]
=== YAML with custom highlight styles

[plantuml, yaml-custom-styles, png]
....
@startyaml
<style>
yamlDiagram {
    highlight {
      BackGroundColor red
      FontColor white
      FontStyle italic
    }
}
</style>
#highlight "french-hens"
#highlight "xmas-fifth-day" / "partridges"
doe: "a deer, a female deer"
ray: "a drop of golden sun"
pi: 3.14159
xmas: true
french-hens: 3
calling-birds:
    - huey
    - dewey
    - louie
    - fred
xmas-fifth-day:
    calling-birds: four
    french-hens: 3
    golden-rings: 5
    partridges:
        count: 1
        location: "a pear tree"
    turtle-doves: two
@endyaml
....


== PlantUML WBS Diagrams

[.maxed-image]
=== Basic OrgMode syntax

[plantuml, wbs-basic, png]
....
@startwbs
* Business Process Modelling WBS
** Launch the project
*** Complete Stakeholder Research
*** Initial Implementation Plan
** Design phase
*** Model of AsIs Processes Completed
**** Model of AsIs Processes Completed1
**** Model of AsIs Processes Completed2
*** Measure AsIs performance metrics
*** Identify Quick Wins
** Complete innovate phase
@endwbs
....

[.maxed-image]
=== Change direction

[plantuml, wbs-direction, png]
....
@startwbs
* Business Process Modelling WBS
** Launch the project
*** Complete Stakeholder Research
*** Initial Implementation Plan
** Design phase
*** Model of AsIs Processes Completed
****< Model of AsIs Processes Completed1
****> Model of AsIs Processes Completed2
***< Measure AsIs performance metrics
***< Identify Quick Wins
@endwbs
....

[.maxed-image]
=== Arithmetic notation

[plantuml, wbs-arithmetic, png]
....
@startwbs
+ New Job
++ Decide on Job Requirements
+++ Identity gaps
+++ Review JDs
++++ Sign-Up for courses
++++ Volunteer
++++ Reading
++- Checklist
+++- Responsibilities
+++- Location
++ CV Upload Done
+++ CV Updated
++++ Spelling & Grammar
++++ Check dates
---- Skills
+++ Recruitment sites chosen
@endwbs
....

[.maxed-image]
=== Multilines with icons

[plantuml, wbs-multilines, png]
....
@startwbs
* <&flag> Debian
** <&globe> Ubuntu
***:Linux Mint
Open Source;
*** Kubuntu
*** Lubuntu
@endwbs
....

[.maxed-image]
=== Boxless nodes

[plantuml, wbs-boxless, png]
....
@startwbs
+ Project
 + Part One
  + Task 1.1
   - LeftTask 1.2
   + Task 1.3
  + Part Two
   + Task 2.1
   + Task 2.2
   -_ Task 2.2.1 To the left boxless
   -_ Task 2.2.2 To the Left boxless
   +_ Task 2.2.3 To the right boxless
@endwbs
....

[.maxed-image]
=== Color and style

[plantuml, wbs-colors, png]
....
@startwbs
<style>
wbsDiagram {
  .pink {
      BackgroundColor pink
  }
  .your_style_name {
      BackgroundColor SkyBlue
  }
}
</style>
* this is the partner workpackage <<your_style_name>>
** this is my workpackage <<pink>>
**:This is on multiple
lines; <<pink>>
** this is another workpackage
@endwbs
....

[.maxed-image]
=== Advanced styling

[plantuml, wbs-advanced-styling, png]
....
@startwbs
<style>
wbsDiagram {
  Linecolor black
  arrow {
    LineColor green
  }
  :depth(0) {
    BackgroundColor White
    RoundCorner 10
    LineColor red
  }
  node {
    :depth(2) {
      LineStyle 2
      LineThickness 2.5
    }
  }
  boxless {
    FontColor darkgreen
  }
}
</style>
* World
** America
*** Canada
*** Mexico
**** Chihuahua
*** USA
**** Texas
***< New York
** Europe
***_ England
***_ Germany
***_ Spain
@endwbs
....


== PlantUML Math Diagrams

[.maxed-image]
=== Standalone AsciiMath formula

[plantuml, math-ascii, png]
....
@startmath
f(t)=(a_0)/2 + sum_(n=1)^ooa_ncos((npit)/L)+sum_(n=1)^oo b_n\ sin((npit)/L)
@endmath
....

[.maxed-image]
=== Standalone LaTeX formula

[plantuml, math-latex, png]
....
@startlatex
\sum_{i=0}^{n-1} (a_i + b_i^2)
@endlatex
....

[.maxed-image]
=== AsciiMath in activity diagram

[plantuml, math-activity-ascii, png]
....
@startuml
:<math>int_0^1f(x)dx</math>;
:<math>x^2+y_1+z_12^34</math>;
note right
Try also <math>d/dxf(x)=lim_(h->0)(f(x+h)-f(x))/h</math>
<math>P(y|bb"x") or f(bb"x")+epsilon</math>
end note
@enduml
....

[.maxed-image]
=== LaTeX in activity diagram

[plantuml, math-activity-latex, png]
....
@startuml
:<latex>\int_0^1f(x)dx</latex>;
:<latex>x^2+y_1+z_{12}^{34}</latex>;
note right
Try also <latex>\dfrac{d}{dx}f(x)=\lim\limits_{h \to 0}\dfrac{f(x+h)-f(x)}{h}</latex>
<latex>P(y|\mathbf{x}) \mbox{ or } f(\mathbf{x})+\epsilon</latex>
end note
@enduml
....

[.maxed-image]
=== Math in sequence diagram

[plantuml, math-sequence, png]
....
@startuml
Bob -> Alice : Can you solve: <math>ax^2+bx+c=0</math>
Alice --> Bob: <math>x = (-b+-sqrt(b^2-4ac))/(2a)</math>
@enduml
....

== PlantUML Chronology Diagrams

[.maxed-image]
=== Basic chronology diagram

[plantuml, chronology-basic, png]
....
@startchronology
title Chronology Diagram
[A: 2024-01-15 01:08:12] happens on 2024-01-15 01:08:12
[B] happens on 2024-01-15 13:08:12
[C] happens on 2024-01-15 22:12:08
@endchronology
....

== PlantUML ArchiMate Diagrams

[.maxed-image]
=== Basic ArchiMate element

[plantuml, archimate-basic, png]
....
@startuml
archimate #Technology "VPN Server" as vpnServerA <<technology-device>>  
rectangle GO #lightgreen 
rectangle STOP #red 
rectangle WAIT #orange 
@enduml
....

[.maxed-image]
=== ArchiMate with junctions

[plantuml, archimate-junctions, png]
....
@startuml
!define Junction_Or circle #black 
!define Junction_And circle #whitesmoke  

Junction_And JunctionAnd 
Junction_Or JunctionOr  

archimate #Technology "VPN Server" as vpnServerA <<technology-device>>  
rectangle GO #lightgreen 
rectangle STOP #red 
rectangle WAIT #orange 

GO -up-> JunctionOr 
STOP -up-> JunctionOr 
STOP -down-> JunctionAnd 
WAIT -down-> JunctionAnd 
@enduml
....

[.maxed-image]
=== Business process example

[plantuml, archimate-business-process, png]
....
@startuml
skinparam rectangle<<behavior>> {
	roundCorner 25 
}
sprite $bProcess jar:archimate/business-process 
sprite $aService jar:archimate/application-service 
sprite $aComponent jar:archimate/application-component  

rectangle "Handle claim" as HC <<$bProcess>><<behavior>> #Business 
rectangle "Capture Information" as CI <<$bProcess>><<behavior>> #Business 
rectangle "Notify\nAdditional Stakeholders" as NAS <<$bProcess>><<behavior>> #Business 
rectangle "Validate" as V <<$bProcess>><<behavior>> #Business 
rectangle "Investigate" as I <<$bProcess>><<behavior>> #Business 
rectangle "Pay" as P <<$bProcess>><<behavior>> #Business  

HC *-down- CI 
HC *-down- NAS 
HC *-down- V 
HC *-down- I 
HC *-down- P  

CI -right->> NAS 
NAS -right->> V 
V -right->> I 
I -right->> P  
@enduml
....

[.maxed-image]
=== Multi-layer enterprise architecture

[plantuml, archimate-multi-layer, png]
....
@startuml
skinparam rectangle<<behavior>> {
    roundCorner 25
}
sprite $bProcess jar:archimate/business-process
sprite $aService jar:archimate/application-service
sprite $aComponent jar:archimate/application-component

rectangle "Handle claim" as HC <<$bProcess>><<behavior>> #Business
rectangle "Capture Information" as CI <<$bProcess>><<behavior>> #Business
rectangle "Validate" as V <<$bProcess>><<behavior>> #Business
rectangle "Investigate" as I <<$bProcess>><<behavior>> #Business
rectangle "Pay" as P <<$bProcess>><<behavior>> #Business

rectangle "Scanning" as scanning <<$aService>><<behavior>> #Application
rectangle "Claims administration" as claimsAdministration <<$aService>><<behavior>> #Application
rectangle Payment <<$aService>><<behavior>> #Application

rectangle "Document Management System" as DMS <<$aComponent>> #Application
rectangle "Home & Away Policy Administration" as HAPA <<$aComponent>> #Application

HC *-down- CI
HC *-down- V
V -right->> I
I -right->> P

scanning -up-> CI
claimsAdministration -up-> V
Payment -up-> P

DMS .up.|> scanning
HAPA .up.|> claimsAdministration
@enduml
....

[.maxed-image]
=== ArchiMate relationships overview

[plantuml, archimate-relationships, png]
....
@startuml
!include <archimate/Archimate>
left to right direction

Motivation_Stakeholder(StakeholderElement, "Stakeholder Description")
Business_Service(BService, "Business Service")
Rel_Composition_Down(StakeholderElement, BService, "Relationship Description")
@enduml
....

== Other Non-PlantURM Diagrams

=== Packet Diagram 
[packetdiag, packet-diagram, png]
....
packetdiag {
  colwidth = 32;
  node_height = 72;

  0-15: Source Port;
  16-31: Destination Port;
  32-63: Sequence Number;
  64-95: Acknowledgment Number;
  96-99: Data Offset;
  100-103: Reserved;
  104: CWR [rotate = 270];
  105: ECE [rotate = 270];
  106: URG [rotate = 270];
  107: ACK [rotate = 270];
  108: PSH [rotate = 270];
  109: RST [rotate = 270];
  110: SYN [rotate = 270];
  111: FIN [rotate = 270];
  112-127: Window;
  128-143: Checksum;
  144-159: Urgent Pointer;
  160-191: (Options and Padding);
  192-223: data [colheight = 3];
}
....

[.maxed-image]
=== Blockdiag Diagram 

[blockdiag, blockdiag-diagram, png]
....
blockdiag {
  blockdiag -> generates -> "block-diagrams";
  blockdiag -> is -> "very easy!";

  blockdiag [color = "greenyellow"];
  "block-diagrams" [color = "pink"];
  "very easy!" [color = "orange"];
}
....


=== Graphviz Diagram 

[graphviz, graphviz-diagram, png]
....
digraph "unix" {
  graph [ fontname = "Helvetica-Oblique",
          fontsize = 36,
          label = "\n\n\n\nObject Oriented Graphs\nStephen North, 3/19/93",
          size = "6,6" ];
  node [ shape = polygon,
         sides = 4,
         distortion = "0.0",
         orientation = "0.0",
         skew = "0.0",
         color = white,
         style = filled,
         fontname = "Helvetica-Outline" ];
  "5th Edition" [sides=9, distortion="0.936354", orientation=28, skew="-0.126818", color=salmon2];
  "6th Edition" [sides=5, distortion="0.238792", orientation=11, skew="0.995935", color=deepskyblue];
  "PWB 1.0" [sides=8, distortion="0.019636", orientation=79, skew="-0.440424", color=goldenrod2];
  LSX [sides=9, distortion="-0.698271", orientation=22, skew="-0.195492", color=burlywood2];
  "1 BSD" [sides=7, distortion="0.265084", orientation=26, skew="0.403659", color=gold1];
  "Mini Unix" [distortion="0.039386", orientation=2, skew="-0.461120", color=greenyellow];
  Wollongong [sides=5, distortion="0.228564", orientation=63, skew="-0.062846", color=darkseagreen];
  Interdata [distortion="0.624013", orientation=56, skew="0.101396", color=dodgerblue1];
  "Unix/TS 3.0" [sides=8, distortion="0.731383", orientation=43, skew="-0.824612", color=thistle2];
  "PWB 2.0" [sides=6, distortion="0.592100", orientation=34, skew="-0.719269", color=darkolivegreen3];
  "7th Edition" [sides=10, distortion="0.298417", orientation=65, skew="0.310367", color=chocolate];
  "8th Edition" [distortion="-0.997093", orientation=50, skew="-0.061117", color=turquoise3];
  "32V" [sides=7, distortion="0.878516", orientation=19, skew="0.592905", color=steelblue3];
  V7M [sides=10, distortion="-0.960249", orientation=32, skew="0.460424", color=navy];
  "Ultrix-11" [sides=10, distortion="-0.633186", orientation=10, skew="0.333125", color=darkseagreen4];
  Xenix [sides=8, distortion="-0.337997", orientation=52, skew="-0.760726", color=coral];
  "UniPlus+" [sides=7, distortion="0.788483", orientation=39, skew="-0.526284", color=darkolivegreen3];
  "9th Edition" [sides=7, distortion="0.138690", orientation=55, skew="0.554049", color=coral3];
  "2 BSD" [sides=7, distortion="-0.010661", orientation=84, skew="0.179249", color=blanchedalmond];
  "2.8 BSD" [distortion="-0.239422", orientation=44, skew="0.053841", color=lightskyblue1];
  "2.9 BSD" [distortion="-0.843381", orientation=70, skew="-0.601395", color=aquamarine2];
  "3 BSD" [sides=10, distortion="0.251820", orientation=18, skew="-0.530618", color=lemonchiffon];
  "4 BSD" [sides=5, distortion="-0.772300", orientation=24, skew="-0.028475", color=darkorange1];
  "4.1 BSD" [distortion="-0.226170", orientation=38, skew="0.504053", color=lightyellow1];
  "4.2 BSD" [sides=10, distortion="-0.807349", orientation=50, skew="-0.908842", color=darkorchid4];
  "4.3 BSD" [sides=10, distortion="-0.030619", orientation=76, skew="0.985021", color=lemonchiffon2];
  "Ultrix-32" [distortion="-0.644209", orientation=21, skew="0.307836", color=goldenrod3];
  "PWB 1.2" [sides=7, distortion="0.640971", orientation=84, skew="-0.768455", color=cyan];
  "USG 1.0" [distortion="0.758942", orientation=42, skew="0.039886", color=blue];
  "CB Unix 1" [sides=9, distortion="-0.348692", orientation=42, skew="0.767058", color=firebrick];
  "USG 2.0" [distortion="0.748625", orientation=74, skew="-0.647656", color=chartreuse4];
  "CB Unix 2" [sides=10, distortion="0.851818", orientation=32, skew="-0.020120", color=greenyellow];
  "CB Unix 3" [sides=10, distortion="0.992237", orientation=29, skew="0.256102", color=bisque4];
  "Unix/TS++" [sides=6, distortion="0.545461", orientation=16, skew="0.313589", color=mistyrose2];
  "PDP-11 Sys V" [sides=9, distortion="-0.267769", orientation=40, skew="0.271226", color=cadetblue1];
  "USG 3.0" [distortion="-0.848455", orientation=44, skew="0.267152", color=bisque2];
  "Unix/TS 1.0" [distortion="0.305594", orientation=75, skew="0.070516", color=orangered];
  "TS 4.0" [sides=10, distortion="-0.641701", orientation=50, skew="-0.952502", color=crimson];
  "System V.0" [sides=9, distortion="0.021556", orientation=26, skew="-0.729938", color=darkorange1];
  "System V.2" [sides=6, distortion="0.985153", orientation=33, skew="-0.399752", color=darkolivegreen4];
  "System V.3" [sides=7, distortion="-0.687574", orientation=58, skew="-0.180116", color=lightsteelblue1];
  "5th Edition" -> "6th Edition";
  "5th Edition" -> "PWB 1.0";
  "6th Edition" -> LSX;
  "6th Edition" -> "1 BSD";
  "6th Edition" -> "Mini Unix";
  "6th Edition" -> Wollongong;
  "6th Edition" -> Interdata;
  Interdata -> "Unix/TS 3.0";
  Interdata -> "PWB 2.0";
  Interdata -> "7th Edition";
  "7th Edition" -> "8th Edition";
  "7th Edition" -> "32V";
  "7th Edition" -> V7M;
  "7th Edition" -> "Ultrix-11";
  "7th Edition" -> Xenix;
  "7th Edition" -> "UniPlus+";
  V7M -> "Ultrix-11";
  "8th Edition" -> "9th Edition";
  "1 BSD" -> "2 BSD";
  "2 BSD" -> "2.8 BSD";
  "2.8 BSD" -> "Ultrix-11";
  "2.8 BSD" -> "2.9 BSD";
  "32V" -> "3 BSD";
  "3 BSD" -> "4 BSD";
  "4 BSD" -> "4.1 BSD";
  "4.1 BSD" -> "4.2 BSD";
  "4.1 BSD" -> "2.8 BSD";
  "4.1 BSD" -> "8th Edition";
  "4.2 BSD" -> "4.3 BSD";
  "4.2 BSD" -> "Ultrix-32";
  "PWB 1.0" -> "PWB 1.2";
  "PWB 1.0" -> "USG 1.0";
  "PWB 1.2" -> "PWB 2.0";
  "USG 1.0" -> "CB Unix 1";
  "USG 1.0" -> "USG 2.0";
  "CB Unix 1" -> "CB Unix 2";
  "CB Unix 2" -> "CB Unix 3";
  "CB Unix 3" -> "Unix/TS++";
  "CB Unix 3" -> "PDP-11 Sys V";
  "USG 2.0" -> "USG 3.0";
  "USG 3.0" -> "Unix/TS 3.0";
  "PWB 2.0" -> "Unix/TS 3.0";
  "Unix/TS 1.0" -> "Unix/TS 3.0";
  "Unix/TS 3.0" -> "TS 4.0";
  "Unix/TS++" -> "TS 4.0";
  "CB Unix 3" -> "TS 4.0";
  "TS 4.0" -> "System V.0";
  "System V.0" -> "System V.2";
  "System V.2" -> "System V.3";
}
....

=== NWDiag Diagram

[nwdiag, nwdiag-diagram, png]
....
nwdiag {
  network dmz {
    address = "210.x.x.x/24"

    web01 [address = "210.x.x.1"];
    web02 [address = "210.x.x.2"];
  }
  network internal {
    address = "172.x.x.x/24";

    web01 [address = "172.x.x.1"];
    web02 [address = "172.x.x.2"];
    db01;
    db02;
  }
}
....


=== UMLet Diagram

[umlet, umlet-diagram, png]
....
<?xml version="1.0" encoding="UTF-8"?>
<umlet_diagram>
    <element>
        <type>com.umlet.element.base.Relation</type>
        <coordinates>
            <x>739</x>
            <y>16</y>
            <w>232</w>
            <h>264</h>
        </coordinates>
        <panel_attributes>lt=&lt;-
when(spidersensor="rotate")
/block spider
        </panel_attributes>
        <additional_attributes>161;244;161;34;71;34;71;74</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.custom.FinalState</type>
        <coordinates>
            <x>890</x>
            <y>260</y>
            <w>20</w>
            <h>20</h>
        </coordinates>
        <panel_attributes></panel_attributes>
        <additional_attributes>transparentSelection=false</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.base.Relation</type>
        <coordinates>
            <x>750</x>
            <y>170</y>
            <w>160</w>
            <h>137</h>
        </coordinates>
        <panel_attributes>lt=&lt;-
after (10s)
/ block spider
        </panel_attributes>
        <additional_attributes>140;100;66;100;66;20</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.custom.State</type>
        <coordinates>
            <x>340</x>
            <y>420</y>
            <w>100</w>
            <h>40</h>
        </coordinates>
        <panel_attributes>wait</panel_attributes>
        <additional_attributes>transparentSelection=false</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.custom.HistoryState</type>
        <coordinates>
            <x>230</x>
            <y>440</y>
            <w>20</w>
            <h>20</h>
        </coordinates>
        <panel_attributes></panel_attributes>
        <additional_attributes>transparentSelection=false</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.base.Relation</type>
        <coordinates>
            <x>230</x>
            <y>416</y>
            <w>130</w>
            <h>54</h>
        </coordinates>
        <panel_attributes>lt=&lt;-
restart
        </panel_attributes>
        <additional_attributes>20;34;110;34</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.base.Relation</type>
        <coordinates>
            <x>270</x>
            <y>396</y>
            <w>90</w>
            <h>54</h>
        </coordinates>
        <panel_attributes>lt=&lt;-
pause
        </panel_attributes>
        <additional_attributes>70;34;20;34</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.custom.FinalState</type>
        <coordinates>
            <x>90</x>
            <y>400</y>
            <w>20</w>
            <h>20</h>
        </coordinates>
        <panel_attributes></panel_attributes>
        <additional_attributes>transparentSelection=false</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.base.Relation</type>
        <coordinates>
            <x>46</x>
            <y>256</y>
            <w>114</w>
            <h>164</h>
        </coordinates>
        <panel_attributes>lt=&lt;-
after (10s)
/timeout
        </panel_attributes>
        <additional_attributes>54;144;54;34;94;34</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.base.Relation</type>
        <coordinates>
            <x>230</x>
            <y>110</y>
            <w>190</w>
            <h>170</h>
        </coordinates>
        <panel_attributes>lt=&lt;-
timeout
        </panel_attributes>
        <additional_attributes>20;150;110;150;110;20;170;20</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.custom.State</type>
        <coordinates>
            <x>700</x>
            <y>90</y>
            <w>180</w>
            <h>100</h>
        </coordinates>
        <panel_attributes>accept
boarding pass
--
entry/ release card
do/release spider
        </panel_attributes>
        <additional_attributes>transparentSelection=true</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.base.Relation</type>
        <coordinates>
            <x>540</x>
            <y>140</y>
            <w>205</w>
            <h>100</h>
        </coordinates>
        <panel_attributes>lt=&lt;-
[passenger booked]
        </panel_attributes>
        <additional_attributes>160;20;120;80;20;80</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.base.Relation</type>
        <coordinates>
            <x>450</x>
            <y>210</y>
            <w>239</w>
            <h>190</h>
        </coordinates>
        <panel_attributes>lt=&lt;-
[passenger not booked]
        </panel_attributes>
        <additional_attributes>219;170;99;170;99;20</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.custom.State</type>
        <coordinates>
            <x>670</x>
            <y>350</y>
            <w>120</w>
            <h>50</h>
        </coordinates>
        <panel_attributes>reject
boarding pass
        </panel_attributes>
        <additional_attributes>transparentSelection=false</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.base.Relation</type>
        <coordinates>
            <x>480</x>
            <y>130</y>
            <w>142</w>
            <h>100</h>
        </coordinates>
        <panel_attributes>lt=&lt;-
result of search
        </panel_attributes>
        <additional_attributes>71;80;71;20</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.base.Relation</type>
        <coordinates>
            <x>270</x>
            <y>70</y>
            <w>150</w>
            <h>40</h>
        </coordinates>
        <panel_attributes>lt=&lt;-</panel_attributes>
        <additional_attributes>130;20;20;20</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.custom.ThreeWayRelation</type>
        <coordinates>
            <x>540</x>
            <y>210</y>
            <w>20</w>
            <h>20</h>
        </coordinates>
        <panel_attributes></panel_attributes>
        <additional_attributes>transparentSelection=false</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.custom.State</type>
        <coordinates>
            <x>140</x>
            <y>60</y>
            <w>150</w>
            <h>420</h>
        </coordinates>
        <panel_attributes>read boarding pass
--
        </panel_attributes>
        <additional_attributes>transparentSelection=true</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.custom.State</type>
        <coordinates>
            <x>400</x>
            <y>60</y>
            <w>180</w>
            <h>90</h>
        </coordinates>
        <panel_attributes>check passenger
--
entry/start search
do/blink lamp
        </panel_attributes>
        <additional_attributes>transparentSelection=true</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.custom.FinalState</type>
        <coordinates>
            <x>170</x>
            <y>410</y>
            <w>20</w>
            <h>20</h>
        </coordinates>
        <panel_attributes></panel_attributes>
        <additional_attributes>transparentSelection=false</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.custom.State</type>
        <coordinates>
            <x>150</x>
            <y>240</y>
            <w>100</w>
            <h>40</h>
        </coordinates>
        <panel_attributes>read
passenger ID
        </panel_attributes>
        <additional_attributes>transparentSelection=false</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.custom.State</type>
        <coordinates>
            <x>150</x>
            <y>330</y>
            <w>100</w>
            <h>40</h>
        </coordinates>
        <panel_attributes>identify
passenger
        </panel_attributes>
        <additional_attributes>transparentSelection=false</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.base.Relation</type>
        <coordinates>
            <x>160</x>
            <y>260</y>
            <w>40</w>
            <h>90</h>
        </coordinates>
        <panel_attributes>lt=&lt;-</panel_attributes>
        <additional_attributes>20;70;20;20</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.base.Relation</type>
        <coordinates>
            <x>160</x>
            <y>100</y>
            <w>40</w>
            <h>70</h>
        </coordinates>
        <panel_attributes>lt=&lt;-</panel_attributes>
        <additional_attributes>20;50;20;20</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.base.Relation</type>
        <coordinates>
            <x>160</x>
            <y>350</y>
            <w>40</w>
            <h>80</h>
        </coordinates>
        <panel_attributes>lt=&lt;-</panel_attributes>
        <additional_attributes>20;60;20;20</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.base.Relation</type>
        <coordinates>
            <x>140</x>
            <y>170</y>
            <w>78</w>
            <h>90</h>
        </coordinates>
        <panel_attributes>lt=&lt;-
[valid]
        </panel_attributes>
        <additional_attributes>39;70;39;20</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.custom.State</type>
        <coordinates>
            <x>150</x>
            <y>150</y>
            <w>100</w>
            <h>40</h>
        </coordinates>
        <panel_attributes>check
validity
        </panel_attributes>
        <additional_attributes>transparentSelection=false</additional_attributes>
    </element>
    <element>
        <type>com.umlet.element.custom.InitialState</type>
        <coordinates>
            <x>170</x>
            <y>100</y>
            <w>20</w>
            <h>20</h>
        </coordinates>
        <panel_attributes></panel_attributes>
        <additional_attributes>transparentSelection=false</additional_attributes>
    </element>
</umlet_diagram>
....